-- Keep in sync with supabase/functions/_shared/exercise-catalog.ts.
insert into exercise (name, movement_pattern, primary_muscles, contraindicated_for) values
  ('Incline Dumbbell Curl', 'isolation', '{biceps}', '{deep_elbow_flexion_loaded}'),
  ('Preacher Curl', 'isolation', '{biceps}', '{deep_elbow_flexion_loaded}'),
  ('Cable Curl', 'isolation', '{biceps}', '{deep_elbow_flexion_loaded}'),
  ('Concentration Curl', 'isolation', '{biceps}', '{deep_elbow_flexion_loaded}'),
  ('Reverse Curl', 'isolation', '{biceps,forearms}', '{deep_elbow_flexion_loaded,loaded_wrist_extension}'),
  ('Tricep Kickback', 'isolation', '{triceps}', '{loaded_elbow_extension}'),
  ('Skull Crusher', 'isolation', '{triceps}', '{loaded_elbow_extension}'),
  ('Close-Grip Bench Press', 'push', '{triceps,chest}', '{heavy_horizontal_press,loaded_elbow_extension}'),
  ('Dumbbell Bench Press', 'push', '{chest}', '{heavy_horizontal_press}'),
  ('Incline Barbell Press', 'push', '{chest,shoulders}', '{heavy_horizontal_press}'),
  ('Chest Fly', 'isolation', '{chest}', '{heavy_horizontal_press}'),
  ('Cable Crossover', 'isolation', '{chest}', '{heavy_horizontal_press}'),
  ('Dumbbell Shoulder Press', 'push', '{shoulders}', '{overhead_press}'),
  ('Arnold Press', 'push', '{shoulders}', '{overhead_press}'),
  ('Front Raise', 'isolation', '{shoulders}', '{}'),
  ('Rear Delt Fly', 'isolation', '{rear_delts}', '{}'),
  ('Upright Row', 'pull', '{shoulders,traps}', '{overhead_press}'),
  ('Shrug', 'isolation', '{traps}', '{}'),
  ('Barbell Row', 'pull', '{back,lats}', '{loaded_spinal_flexion}'),
  ('T-Bar Row', 'pull', '{back,lats}', '{loaded_spinal_flexion}'),
  ('Chest-Supported Row', 'pull', '{back}', '{}'),
  ('Chin-up', 'pull', '{lats,biceps}', '{deep_elbow_flexion_loaded}'),
  ('Straight-Arm Pulldown', 'isolation', '{lats}', '{}'),
  ('Goblet Squat', 'squat', '{quads,glutes}', '{deep_knee_flexion_loaded}'),
  ('Hack Squat', 'squat', '{quads}', '{deep_knee_flexion_loaded,heavy_axial_load}'),
  ('Bulgarian Split Squat', 'squat', '{quads,glutes}', '{deep_knee_flexion_loaded}'),
  ('Walking Lunge', 'squat', '{quads,glutes}', '{deep_knee_flexion_loaded}'),
  ('Step-up', 'squat', '{quads,glutes}', '{deep_knee_flexion_loaded}'),
  ('Sumo Deadlift', 'hinge', '{glutes,hamstrings}', '{heavy_axial_load,loaded_spinal_flexion,deep_hip_flexion_loaded}'),
  ('Trap Bar Deadlift', 'hinge', '{glutes,quads,back}', '{heavy_axial_load}'),
  ('Single-Leg Romanian Deadlift', 'hinge', '{hamstrings,glutes}', '{}'),
  ('Good Morning', 'hinge', '{hamstrings,back}', '{loaded_spinal_flexion,heavy_axial_load}'),
  ('Back Extension', 'hinge', '{back,glutes}', '{loaded_spinal_extension}'),
  ('Cable Glute Kickback', 'isolation', '{glutes}', '{}'),
  ('Hip Abduction', 'isolation', '{glutes}', '{}'),
  ('Seated Calf Raise', 'isolation', '{calves}', '{}'),
  ('Side Plank', 'core', '{core}', '{}'),
  ('Russian Twist', 'core', '{core}', '{loaded_spinal_flexion}'),
  ('Cable Crunch', 'core', '{core}', '{loaded_spinal_flexion}'),
  ('Bicycle Crunch', 'core', '{core}', '{loaded_spinal_flexion}'),
  ('Farmer''s Carry', 'carry', '{core,forearms,traps}', '{heavy_axial_load}'),
  ('Zone 2 Cardio', 'cardio', '{heart}', '{}'),
  ('Treadmill Incline Walk', 'cardio', '{heart,calves}', '{}'),
  ('Stationary Bike', 'cardio', '{heart,quads}', '{}'),
  ('Rowing Machine', 'cardio', '{heart,back}', '{loaded_spinal_flexion}'),
  ('Elliptical', 'cardio', '{heart}', '{}'),
  ('Stair Climber', 'cardio', '{heart,glutes}', '{}'),
  ('Jump Rope', 'cardio', '{heart,calves}', '{high_impact}'),
  ('Running', 'cardio', '{heart}', '{high_impact}')
on conflict (name) do nothing;
